# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hanji.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from deep_translator import GoogleTranslator


class Ui_Hanji(object):
    def setupUi(self, Hanji):
        Hanji.setObjectName("Hanji")
        Hanji.resize(554, 511)
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        Hanji.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Hanji)
        self.centralwidget.setObjectName("centralwidget")
        self.translator = QtWidgets.QTabWidget(self.centralwidget)
        self.translator.setGeometry(QtCore.QRect(20, 10, 511, 451))
        self.translator.setObjectName("translator")
        self.englishtopersian = QtWidgets.QWidget()
        self.englishtopersian.setObjectName("englishtopersian")
        self.input1 = QtWidgets.QPlainTextEdit(self.englishtopersian)
        self.input1.setGeometry(QtCore.QRect(10, 20, 231, 311))
        self.input1.setPlaceholderText("Type here:")
        self.input1.setObjectName("input1")
        self.output1 = QtWidgets.QTextBrowser(self.englishtopersian)
        self.output1.setGeometry(QtCore.QRect(260, 20, 231, 311))
        self.output1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.output1.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.output1.setObjectName("output1")
        self.translate1 = QtWidgets.QPushButton(self.englishtopersian)
        self.translate1.setGeometry(QtCore.QRect(180, 350, 141, 41))
        self.translate1.setObjectName("translate1")
        self.clear1 = QtWidgets.QPushButton(self.englishtopersian)
        self.clear1.setGeometry(QtCore.QRect(20, 352, 71, 31))
        self.clear1.setObjectName("clear1")
        self.translator.addTab(self.englishtopersian, "")
        self.persiantoenglish = QtWidgets.QWidget()
        self.persiantoenglish.setObjectName("persiantoenglish")
        self.output2 = QtWidgets.QTextBrowser(self.persiantoenglish)
        self.output2.setGeometry(QtCore.QRect(260, 20, 231, 311))
        self.output2.setObjectName("output2")
        self.translate2 = QtWidgets.QPushButton(self.persiantoenglish)
        self.translate2.setGeometry(QtCore.QRect(180, 350, 141, 41))
        self.translate2.setObjectName("translate2")
        self.input2 = QtWidgets.QPlainTextEdit(self.persiantoenglish)
        self.input2.setGeometry(QtCore.QRect(10, 20, 231, 311))
        self.input2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.input2.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.input2.setObjectName("input2")
        self.clear2 = QtWidgets.QPushButton(self.persiantoenglish)
        self.clear2.setGeometry(QtCore.QRect(20, 352, 71, 31))
        self.clear2.setObjectName("clear2")
        self.translator.addTab(self.persiantoenglish, "")
        Hanji.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Hanji)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 554, 32))
        self.menubar.setObjectName("menubar")
        Hanji.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Hanji)
        self.statusbar.setObjectName("statusbar")
        Hanji.setStatusBar(self.statusbar)

        self.retranslateUi(Hanji)
        self.translator.setCurrentIndex(0)
        self.translate1.clicked.connect(self.englishtranslate)
        self.translate2.clicked.connect(self.persiantranslate)
        self.clear1.clicked.connect(self.erase1)
        self.clear2.clicked.connect(self.erase2)
        QtCore.QMetaObject.connectSlotsByName(Hanji)

    def englishtranslate(self):
        text = self.input1.toPlainText()
        translated = GoogleTranslator(source='en', target='fa').translate(text)
        self.output1.insertPlainText(translated)
    
    def persiantranslate(self):
        text = self.input2.toPlainText()
        translated = GoogleTranslator(source='fa', target='en').translate(text)
        self.output2.insertPlainText(translated)
    
    def erase1(self):
        self.input1.clear()
        self.output1.clear()
    
    def erase2(self):
        self.input2.clear()
        self.output2.clear()

    def retranslateUi(self, Hanji):
        _translate = QtCore.QCoreApplication.translate
        Hanji.setWindowTitle(_translate("Hanji", "Hanji"))
        Hanji.setWindowIcon(QtGui.QIcon('logo.png'))
        self.translate1.setText(_translate("Hanji", "Translate"))
        self.clear1.setText(_translate("Hanji", "Clear"))
        self.translator.setTabText(self.translator.indexOf(self.englishtopersian), _translate("Hanji", "English To Persian"))
        self.translate2.setText(_translate("Hanji", "ترجمه"))
        self.input2.setPlaceholderText(_translate("Hanji", ":تایپ کنید"))
        self.clear2.setText(_translate("Hanji", "پاک کردن"))
        self.translator.setTabText(self.translator.indexOf(self.persiantoenglish), _translate("Hanji", "Persian To English"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Hanji = QtWidgets.QMainWindow()
    ui = Ui_Hanji()
    ui.setupUi(Hanji)
    Hanji.show()
    sys.exit(app.exec_())